config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  get 'bookings/create'
  get 'bookings/destroy'
  devise_for :users
  root to: 'pages#home'
  resources :skates do
    resources :bookings, only: [:new, :create, :update, :destroy]

    get "status/:id", to: "bookings#status", as: :status
    resources :reviews, only: :create
  end
  # resources :bookings, only: :destroy
  resources :reviews, only: :destroy
  get "compled/:id", to: "bookings#compled", as: :compled
  get "dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :skate
  belongs_to :user
  validates :time_from, :descripcion, presence: true
  validates :time_from, uniqueness: {scope: :skate_id, message: "fecha ya alquilada" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :skate

  validates :comment, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/models/skate.rb
class Skate < ApplicationRecord
  attr_accessor :user_skate_pos
  
  include PgSearch::Model
  belongs_to :user
  has_many :booking
  has_many_attached :photos
  has_many :reviews
  validates :precio_dia, :ubicacion, :photos, :descripcion, :categoria, presence: true

  geocoded_by :ubicacion
  after_validation :geocode, if: :will_save_change_to_ubicacion?

  scope :filter_by_price_desc, -> { order(precio_dia: :desc) }
  scope :filter_by_price_asc, -> { order(precio_dia: :asc) }
  scope :location, -> { order(ubicacion: :asc) }
  scope :search, -> { where("ubicacion LIKE ?", "%#{params[:search]}%") }
  #scope :filter_by_search, -> (ubicacion) { where("ubicacion like ?", "%#{ubicacion}%")}
  scope :filter_by_zona, -> (zona) { where("ubicacion like ?", "%#{zona}%")}

  scope :filter_by_categoria, -> (categoria) { where("categoria like ?", "%#{categoria}%")}
  pg_search_scope :search_by_ubicacion_and_descripcion,
    against: [ :ubicacion, :descripcion ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :skaters
  has_many :bookings  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  include Pagy::Backend
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :skip_authorization, only: [:destroy, :status, :compled]
  before_action :set_skate, only: [:new, :create, :update, :destroy]
  #skip_before_action :
  def new
  end

  def create
    authorize @skate
    @booking = Booking.new(booking_params)
    @booking.skate = @skate
    @booking.price_total = @skate.precio_dia
    @booking.user = current_user
    # @booking.status = true
    # @booking.compled = false
    if @booking.save
      redirect_to skate_path(@skate)
    else
      render 'skates/show'
    end
  end

  def update
  end

  def compled
    @booking = Booking.find(params[:id])
    @booking.compled = true
    @booking.save
    puts params
    redirect_to dashboard_path
  end

  def status
    @booking = Booking.find(params[:id])
    @booking.status = false
    @booking.save
    puts params
    redirect_to skate_path(params[:skate_id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to skates_path
  end

  private

  def booking_params
    params.require(:booking).permit(:skate_id, :time_from, :descripcion)
  end

  def set_skate
    @skate = Skate.find(params[:skate_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def dashboard
    @my_skates = Skate.where(user_id: current_user)
    @my_bookings = Booking.where(user_id: current_user)
    @a = Booking.all
    @rents = @a.select do |book|
      book.skate.user_id == current_user.id
    end
    @pagy, @my_skates = pagy(@my_skates, items: 3)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
      @review = Review.new(review_params)
      @skate = Skate.find(params[:skate_id])
      @review.skate = @skate
      authorize @skate
      if @review.save
        redirect_to skate_path(@skate)
      else
        render 'skates/show'
      end
    end

    def destroy
      @review = Review.find(params[:id])
      @review.destroy
      redirect_to skate_path(@review.skate)
    end

    private

    def review_params
      params.require(:review).permit(:comment, :rating)
    end

end

app/controllers/skates_controller.rb
require 'user_ip'

class SkatesController < ApplicationController
  before_action :set_skate, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @skates = policy_scope(Skate.all)
    @skates = Skate.filter_by_price_desc if (params[:filter] == "price-desc")
    @skates = Skate.filter_by_price_asc if (params[:filter] == "price-asc")
    @skates = Skate.location if (params[:filter] == "ubicacion")
    @skates = @skates.filter_by_zona(params[:zona]) if params[:zona]

    @skates = @skates.filter_by_categoria(params[:categoria]) if params[:categoria]
    @skates = @skates.search_by_ubicacion_and_descripcion(params[:search]) if params[:search].present?
    @pagy, @skates = pagy(@skates, items: 8)
    @skates.each do |skate|
      if skate.present?
        usuario = UserIp.new(skate)
        skate.user_skate_pos = usuario.distancia
      end
    end
    @skates = @skates.sort_by { |skate| skate.user_skate_pos } if (params[:filter] == "cercania")


  end

  def show
    @booking = Booking.new
    usuario = UserIp.new(@skate)
    @review = Review.new(skate: @skate)
    @marker_skate = {
                lat: @skate.latitude,
                lng: @skate.longitude,
                info_window: render_to_string(partial: "info_window", locals: { skate: @skate })
              }

    @marker_user = {
                lat: usuario.user_pos[0],
                lng: usuario.user_pos[1],
              }


    @reservado = false
    @review_act = false
    @reserva = nil
    @reserva = Booking.find_by(skate_id: @skate, user_id: current_user, status: true, compled: false)
    if @reserva.present?
      @reservado = true
      @booking = Booking.find_by(skate_id: @skate, user_id: current_user, status: true, compled: false)
      @c_u = current_user.id
    end
    if Booking.find_by(skate_id: @skate, user_id: current_user, status: false, compled: true)
      @review_act = true
    end
  end

  def new
    @skate = Skate.new
    authorize @skate
  end

  def create
    @skate = Skate.new(skate_params)
    @skate.user = current_user
    authorize @skate
    if @skate.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def update
  end

  def edit
  end

  def destroy
    @skate.destroy
    redirect_to dashboard_path
  end

  private

  def set_skate
    @skate = Skate.find(params[:id])
    authorize @skate
  end

  def skate_params
    params.require(:skate).permit(:precio_dia, :ubicacion, :descripcion, :categoria, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/user_ip.rb
require 'json'
require 'open-uri'

class UserIp
    def initialize(skate)
        url = 'https://api.ipify.org/?format=json'
        user_serialized = URI.open(url).read
        @ip = JSON.parse(user_serialized)["ip"]
        results = Geocoder.search(@ip)
        @user_pos = results.first.coordinates
        @skate_pos = [skate.latitude, skate.longitude]
        @distancia = Geocoder::Calculations.distance_between(user_pos,skate_pos, :units => :km).round(2)
    end

    attr_reader :ip, :distancia, :user_pos, :skate_pos
  end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veskaters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://image.flaticon.com/icons/png/512/613/613969.png" rel="icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.5.1/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.5.1/mapbox-gl.js"></script>
    <script src='https://unpkg.com/@turf/turf/turf.min.js'></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_card.html.erb
<div class="card mb-4" style="width: 18rem;">
    <div class = "card-image card-img-top">
        <%= render "carousel", images: images, id_name: id_name%>
    </div>
    <div class="card-body">
        <div class = "d-flex justify-content-between">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">$5/dia</p>
        </div>
        <div class = "d-flex justify-content-between">
            <h6 class="card-subtitle text-muted mt-1">Distancia</h6>
            <div class = "d-flex justify-content-between mt-1">
                <i class="fas fa-star star-yellow"></i>
                <i class="fas fa-star star-yellow"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                </div>                
            </div>                               
        </div>
    </div>

app/views/pages/dashboard.html.erb
<%= render "/shared/navbar2" %>
<div class = container>
    <div class = "d-flex justify-content-between">
        <div class = "profile">
            <div class="card mt-4">
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "img-top rounded-circle align-self-center", alt: "avatar-large", width: "100px" %>
                <div class="card-body">
                    <h5 class="card-title"><%=current_user.email.match(/\w+/)[0]%></h5>
                    <p class="card-text"></p>
                    <%= link_to "Editar profile", class: "btn btn-primary"%>
                </div>
            </div>
        </div>
        <div class = "mt-4">
            <% if user_signed_in? %>
                <%= link_to new_skate_path, class: "btn btn-lg", style: "border-radius: 15px; color: white; background: #ffc107;" do %>
                    <i class="far fa-plus-square"></i> Agregar
                <% end %>
            <% end %>
        </div>
    </div>


<h1>Mis Skate</h1>   
    <div class = "cards row d-flex justify-content-around mt-4 pt-3">
        <%@my_skates.each do |skate| %>         
            <div class="mb-3 col-12 col-sm-6 col-lg-3">             
                <%= render "shared/card-dash", skate: skate%>                 
            </div>          
        <% end %>
    </div>
    <div class="d-flex justify-content-center mt-3">
        <%== pagy_bootstrap_nav(@pagy) %>
    </div>
</div>


<h1>Mis rantas</h1>
<table>
  <th>usuario</th><th>Fecha</th><th>status</th><th>completada</th>
<% @rents.each do |rent| %>
  <tr><td><%=   rent.user.email %></td><td><%=   rent.time_from %></td><td><%=  rent.status %></td><td><%= rent.compled %></td>
  <% if !rent.compled  %>
    <td><%= link_to "completado", compled_path(rent), class: "btn btn-primary"%></td> </tr>
  <% end %>
<% end %>
</table>
</div>

app/views/pages/home.html.erb
<%= render "shared/navbar" %>
<%= render "shared/banner" %>
<%= render "shared/gotop" %>
<div class="contenedor">
  <h2 class="mt-5">Explora cerca de ti</h2>

<div class="row mb-5">
  <div class="mb-3 col-12 col-sm-6 col-lg-3">
    <%= link_to skates_path(zona: "Chacao") do %>
    <div class="row">
      <div class="col-4">
        <img src="https://th.bing.com/th/id/R.d0c72e0aedd5cf182aec9c529edb3e03?rik=tU721p1B6gVf8A&riu=http%3a%2f%2fmmedia.eluniversal.com%2f18086%2fmunicipiochacao-28362.jpg&ehk=HRR7GYJtmx%2fKu678N8eqcJhp5kxEkMO3%2fATs3wVn15U%3d&risl=&pid=ImgRaw&r=0" alt="" style="width:90px; height: 80px; border-radius: 10px;">
      </div>
      <div class="col-8">
        <h5>Chacao</h5>
        <p>15 minutos</p>
      </div>
    </div>
    <% end %>
  </div>
  <div class="mb-3 col-12 col-sm-6 col-lg-3" style="max-width: 540px;">
    <%= link_to skates_path(zona: "Zoologico") do %>
    <div class="row justify-content-between">
      <div class="col-4">
        <img src="https://th.bing.com/th/id/OIP.aOm4n4KrIY6D2qeOBafyCQHaEa?pid=ImgDet&rs=1" alt="" style="width:90px; height: 80px; border-radius: 10px;">
      </div>
      <div class="col-8">
        <h5>SkatePark Zoologico</h5>
        <p>15 minutos</p>
      </div>
    </div>
     <% end %>
  </div>
    <div class="mb-3 col-12 col-sm-6 col-lg-3" style="max-width: 540px;">
      <%= link_to skates_path(zona: "Los proceres") do %>
        <div class="row">
          <div class="col-4">
            <img src="https://th.bing.com/th/id/OIP.9MUuMW1qXAlMbgwfUO9iPwHaJ4?pid=ImgDet&rs=1" alt="" style="width:90px; height: 80px; border-radius: 10px;">
          </div>
          <div class="col-8">
            <h5>Los Proceres</h5>
            <p>40 minutos</p>
          </div>
        </div>
      <% end %>
  </div>
  <div class="mb-3 col-12 col-sm-6 col-lg-3" style="max-width: 540px;">
    <%= link_to skates_path(zona: "Cota 1000") do %>
    <div class="row">
      <div class="col-4">
        <img src="https://i.pinimg.com/originals/4e/bd/3b/4ebd3b440ed8ae63551ac1f86117056e.jpg" alt="" style="width:90px; height: 80px; border-radius: 10px;">
      </div>
      <div class="col-8">
        <h5>Cota 1000</h5>
        <p>35 minutos</p>
      </div>
    </div>
    <% end %>
  </div>
    <div class="mb-3 col-12 col-sm-6 col-lg-3">
      <%= link_to skates_path(zona: "La urbina") do %>
      <div class="row">
        <div class="col-4">
          <img src="https://th.bing.com/th/id/R.8cd06eefc9afeead7b6f64843c4d0b48?rik=C09kGbggHdEhLA&pid=ImgRaw&r=0" alt="" style="width:90px; height: 80px; border-radius: 10px;">
        </div>
        <div class="col-8">
          <h5>La urbina</h5>
          <p>8 minutos</p>
        </div>
      </div>
      <% end %>
  </div>
  <div class="mb-3 col-12 col-sm-6 col-lg-3" style="max-width: 540px;">
    <%= link_to skates_path(zona: "El marques") do %>
    <div class="row">
      <div class="col-4">
        <img src="https://img10.naventcdn.com/avisos/13/00/51/96/31/75/1200x1200/54639212.jpg" alt="" style="width:90px; height: 80px; border-radius: 10px;">
      </div>
      <div class="col-8">
        <h5>El marques</h5>
        <p>105 minutos</p>
      </div>
    </div>
     <% end %>
  </div>
    <div class="mb-3 col-12 col-sm-6 col-lg-3" style="max-width: 540px;">
      <%= link_to skates_path(zona: "La trinidad") do %>
        <div class="row">
          <div class="col-4">
            <img src="https://i.pinimg.com/originals/c1/da/60/c1da60e4c912634c133087fb09897f15.jpg" alt="" style="width:90px; height: 80px; border-radius: 10px;">
          </div>
          <div class="col-8">
            <h5>La trinidad</h5>
            <p>73 minutos</p>
          </div>
        </div>
      <% end %>
  </div>
  <div class="mb-3 col-12 col-sm-6 col-lg-3" style="max-width: 540px;">
    <%= link_to skates_path(zona: "El paraiso") do %>
    <div class="row">
      <div class="col-4">
        <img src="https://th.bing.com/th/id/R.90a8bf8e2e5555dc9d259950f3c1098f?rik=j4DVE3srf0NUcg&riu=http%3a%2f%2fguiaccs.com%2fwp-content%2fuploads%2f2017%2f09%2f106_Tarjetas-Z3.jpg&ehk=HRcfHjA5D5I7P1px3FnTnVqsobZRkoAuvAanoKsHOto%3d&risl=&pid=ImgRaw&r=0" alt="" style="width:90px; height: 80px; border-radius: 10px;">
      </div>
      <div class="col-8">
        <h5>El paraiso</h5>
        <p>45 segundos</p>
      </div>
    </div>
    <% end %>
  </div>
</div>

<h2 class="mb-5">Nuestros productos.</h2>

<div class="cards-home mb-5">
  <%= link_to skates_path(categoria: "Patineta") do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://th.bing.com/th/id/OIP.eJQtn36Wyvufv3LiVBY8PwHaE8?pid=ImgDet&w=640&h=427&rs=1)">
      Patinetas
    </div>
  <% end %>
  <%= link_to skates_path(categoria: "Bicicleta") do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.hibridosyelectricos.com/media/hibridos/images/2020/11/05/2020110515560802634.jpg)">
      Bicicleta
    </div>
  <% end %>
  <%= link_to skates_path(categoria: "Patines") do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://th.bing.com/th/id/OIP.IsbPmxg9m8k2DApxj2_k-QHaHa?pid=ImgDet&rs=1)">
      Patines
    </div>
  <% end %>
  <%= link_to skates_path(categoria: "Monopatin") do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://360scooters.com/wp-content/uploads/2020/12/swissgo-PT010_4-600x600-1.jpg)">
      Monopatin
    </div>
  <% end %>
</div>

<div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://www.lakewanaka.co.nz/assets/Tourism-Operators/images/20150829-pedropimentel-net-Wanaka-Skate-Park-Opening-451.jpg);">
  <div class="container">
    <h1>Conoce la historia del skate.</h1>
    <p>El monopatinaje,s un deporte que consiste en deslizarse sobre un monopatín y a la vez poder realizar diversos trucos, gran parte de ellos elevando la tabla del suelo, haciendo piruetas con ella en el aire.</p>
    <a class="btn btn-primary" href="https://www.historiadetudo.com/historia-do-skate#:~:text=A%20hist%C3%B3ria%20do%20skate%20surgiu%20a%20partir%20de,n%C3%A3o%20dava%20para%20surfar%20de%20verdade%20%28baixa%20mar%C3%A9%29." target="_blank">Ver link</a>
  </div>
</div>

</div>

app/views/shared/_banner.html.erb
<div class="home-banner">
  <h1>VeSkaters</h1>
  <p>
    <span id="banner-typed-text" style="color: black"></span>
  </p>

  <div class="box" id="box">
    <form action="skates/" method="get">
      <input type="text" name="search" placeholder="   Type...">
      <input type="submit" name="" value="Search">
    </form>
  </div>

</div>

app/views/shared/_card-dash.html.erb
<div class="card">
    <div class = "card-image card-img-top">
        <%= render "shared/carousel", photos: skate.photos, id_name: skate.id%>
    </div>
    <div class="card-body">
        <div class = "d-flex justify-content-between">
            <h5 class="card-title"><%=skate.ubicacion%></h5>
            <p class="card-text">$<%=skate.precio_dia%>/dia</p>
        </div>

        <div class = "d-flex justify-content-between">
            <div>
                <%= link_to "Editar", edit_skate_path(skate) %>
                <%= link_to "Eliminar", skate_path(skate), method: :delete, data: {confirm: "Estas seguro?"}, class:"text-danger" %>
            </div>
            <div class = "d-flex justify-content-between ml-2">
                <% rating = skate.reviews.reduce(0) do |sum, review|%>
                    <% sum + review.rating%>
                <%end%>
                <h6>Rating:</h6>
                <%if (skate.reviews.size.zero?) %>
                    <% 5.times do |x|%>
                        <i class="far fa-star"></i>
                    <%end%>
                <%else%>
                    <%(rating.div(skate.reviews.size)).times do |x|%>
                        <i class="fas fa-star"></i>
                    <%end%>
                    <%(5 - rating.div(skate.reviews.size)).times do |x|%>
                        <i class="far fa-star"></i>
                    <%end%>
                <%end%>

            </div>
        </div>       
    </div>
</div>

app/views/shared/_card.html.erb
<div class="card">
    <div class = "card-image card-img-top">
        <%= render "shared/carousel", photos: skate.photos, id_name: skate.id%>
    </div>
    <div class="card-body">
        <div class = "d-flex justify-content-between">
            <h5 class="card-title"><%=skate.ubicacion%></h5>
            <p class="card-text">$<%=skate.precio_dia%>/dia</p>
        </div>

        <div class = "d-flex justify-content-between">
            <div>
                <%= link_to "Rentar", skate_path(skate) %>
            </div>
            <div class = "d-flex justify-content-between ml-2">
                <% rating = skate.reviews.reduce(0) do |sum, review|%>
                    <% sum + review.rating%>
                <%end%>
                <h6>Rating:</h6>
                <%if (skate.reviews.size.zero?) %>
                    <% 5.times do |x|%>
                        <i class="far fa-star"></i>
                    <%end%>
                <%else%>
                    <%(rating.div(skate.reviews.size)).times do |x|%>
                        <i class="fas fa-star"></i>
                    <%end%>
                    <%(5 - rating.div(skate.reviews.size)).times do |x|%>
                        <i class="far fa-star"></i>
                    <%end%>
                <%end%>

            </div>
        </div>
        <h6 class="card-subtitle text-muted mt-1" id="card-distancia">
            Distancia: <%=skate.user_skate_pos%>Km </h6>
    </div>
</div>

app/views/shared/_cardbookingnew.html.erb
<div class="map-card card mb-3 col-6">
      <div class="card-body">
      <% if reservado %>
        <h5 class="card-title">Tu reserva</h5>
        <p class="card-text">Detalles:
        <ul>
          <li>Rendador= <%= booking.skate.user.email %></li>
          <li>Fecha = <%= booking.time_from %></li>
          <li>Ubicación= <%= booking.skate.ubicacion %></li>
          <li>Precio= <%= booking.skate.precio_dia %> $</li>
        </ul>
        </p>
        <hr>
        <%= link_to "Cancelar", skate_booking_path(skate,booking), class: "btn btn-primary", method: :delete, data: {confirm: "estas seguro"} %>


      <% else  %>
        <%= simple_form_for [skate, booking] do |f| %>
          <%= f.input :time_from, label: "fecha de reserva"%>
          <%= f.input :descripcion, label: "nota:" %>
          <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>

app/views/shared/_carousel.html.erb
<div id="carousel<%=id_name%>" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel<%=id_name%>" data-slide-to="0" class="active"></li>
    <li data-target="#carousel<%=id_name%>" data-slide-to="1"></li>
    <li data-target="#carousel<%=id_name%>" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">   
    <div class="carousel-item active">
      <%= cl_image_tag photos[0].key, width: 100, height: 200, class:"d-block w-100 p-1" %>
    </div>
    <%photos[1..-1].each do |photo| %>
      <div class="carousel-item">
        <%= cl_image_tag photo.key, width: 100, height: 200, class:"d-block w-100 p-1"%>
      </div>
    <% end %>     
  </div>
  <a class="carousel-control-prev" href="#carousel<%=id_name%>" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel<%=id_name%>" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_carouselShow.html.erb
<div id="carousel<%=id_name%>" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel<%=id_name%>" data-slide-to="0" class="active"></li>
    <li data-target="#carousel<%=id_name%>" data-slide-to="1"></li>
    <li data-target="#carousel<%=id_name%>" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">   
    <div class="carousel-item active">
      <%= cl_image_tag photos[0].key, width: 200, height: 300, class:"d-block w-100 p-1"%>
    </div>
    <%photos[1..-1].each do |photo| %>
      <div class="carousel-item">
        <%= cl_image_tag photo.key, width: 200, height: 300, class:"d-block w-100 p-1"%>
      </div>
    <% end %>     
  </div>
  <a class="carousel-control-prev" href="#carousel<%=id_name%>" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel<%=id_name%>" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_gotop.html.erb
<button class="go-top-btn">
  <%= image_tag "up.png", alt: "Le Wagon" %>
</button>

app/views/shared/_map.html.erb
<div class = "mapa" id='map'
    data-marker-skate="<%= @marker_skate.to_json %>"
    data-marker-user="<%= @marker_user.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">    
</div>

<div id='map-overlay'>Distance: </div>

app/views/skates/_info_window.html.erb
<h2><%= skate.descripcion %></h2>
<p><%= skate.ubicacion %></p>